version: "0.2"
ignorePaths:
  - .vscode/
  - devcontainer.json
  - cspell.config.yaml
dictionaryDefinitions: []
words:
  - bicepconfig
  - Codespace
  - Codespaces
  - devcontainer
  - psrule
  - sarif
  - winget
ignoreWords: []
import: []
language: en,en-GB
enabled: true
description: |
  This configuration defines the default spellcheck settings for this workspace.
validateDirectives: true
dictionaries:
  - azureTerms
  - companies
  - filetypes
  - misc
  - powershell
  - softwareTerms
