#
# Analyze repository with PSRule
#

# For PSRule documentation see:
# https://aka.ms/ps-rule

# For action details see:
# https://aka.ms/ps-rule-action

name: Analyze with PsRule

# Run for main or PRs against main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run analysis by using the PSRule GitHub action.
      - name: Run PSRule analysis
        uses: microsoft/ps-rule@v2.9.0
        with:
          modules: PSRule.Rules.Azure
